name: GCD Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up permission
      run: chmod +x gcd.sh test_gcd.sh
    - name: Run tests
      run: ./test_gcd.sh
